import {
  Sparkles,
  Home,
  UtensilsCrossed,
  ShoppingCart,
  Bus,
  Stethoscope,
  Zap,
  Plane,
  Wallet,
  Coins,
  Gift,
  PiggyBank,
  BookOpen,
  Car,
  Film,
  Repeat,
  Palette,
  Coffee,
  Pizza,
  Salad,
  Wine,
  Beef,
  IceCream,
  CakeSlice,
  Apple,
  Candy,
  Cookie,
  Milk,
  Egg,
  Train,
  Bike,
  CarTaxiFront,
  Ship,
  Fuel,
  ParkingCircle,
  ShoppingBag,
  Store,
  Shirt,
  Watch,
  Gem,
  Package,
  Briefcase,
  Landmark,
  Building,
  Building2,
  Warehouse,
  Hotel,
  Trees,
  Flower,
  Sofa,
  Bed,
  Lamp,
  Tv,
  Heart,
  Pill,
  Syringe,
  Activity,
  HeartPulse,
  Dumbbell,
  Music,
  Headphones,
  Mic,
  Gamepad2,
  Tv2,
  Theater,
  PartyPopper,
  Ticket,
  Camera,
  Smartphone,
  Laptop,
  Monitor,
  Wifi,
  Phone,
  Mail,
  MessageSquare,
  Newspaper,
  Book,
  GraduationCap,
  School,
  Pencil,
  Scissors,
  Ruler,
  Calculator,
  Globe,
  MapPin,
  Compass,
  Mountain,
  Tent,
  Palmtree,
  Waves,
  Umbrella,
  Sun,
  Cloud,
  Snowflake,
  Baby,
  Dog,
  Cat,
  PawPrint,
  Bone,
  Bird,
  Fish,
  CircleDollarSign,
  CreditCard,
  Receipt,
  Banknote,
  TrendingUp,
  TrendingDown,
  ChartBar,
  Target,
  Award,
  Trophy,
  Star,
  Flag,
  Wrench,
  Hammer,
  Paintbrush,
  Brush,
  Droplet,
  Flame,
  Leaf,
  Recycle,
  TreePine,
  Sprout,
  HandHeart,
  HandCoins,
  Users,
  UserCircle,
  Rocket,
  Lightbulb,
  Settings,
  Shield,
  Lock,
  Key,
  FileText,
  ClipboardList,
  Calendar,
  Clock,
  Bell,
  CircleHelp,
  CirclePlus,
} from "lucide-react";

export const CATEGORY_ICON_KEYS = [
  "spark",
  "house",
  "food",
  "cart",
  "bus",
  "hospital",
  "utility",
  "travel",
  "wallet",
  "salary",
  "gift",
  "savings",
  "study",
  "car",
  "entertainment",
  "subscription",
  "hobby",
  "coffee",
  "pizza",
  "salad",
  "wine",
  "beef",
  "ice-cream",
  "cake",
  "apple",
  "candy",
  "cookie",
  "milk",
  "egg",
  "train",
  "bike",
  "taxi",
  "ship",
  "fuel",
  "parking",
  "shopping-bag",
  "store",
  "shirt",
  "watch",
  "gem",
  "package",
  "briefcase",
  "landmark",
  "building",
  "building-2",
  "warehouse",
  "hotel",
  "trees",
  "flower",
  "sofa",
  "bed",
  "lamp",
  "tv-unit",
  "heart",
  "pill",
  "syringe",
  "activity",
  "heart-pulse",
  "dumbbell",
  "music",
  "headphones",
  "microphone",
  "gamepad",
  "tv",
  "theater",
  "party",
  "ticket",
  "camera",
  "smartphone",
  "laptop",
  "monitor",
  "wifi",
  "phone",
  "mail",
  "message",
  "newspaper",
  "book",
  "graduation",
  "school",
  "pencil",
  "scissors",
  "ruler",
  "calculator",
  "globe",
  "map-pin",
  "compass",
  "mountain",
  "tent",
  "palm-tree",
  "waves",
  "umbrella",
  "sun",
  "cloud",
  "snowflake",
  "baby",
  "dog",
  "cat",
  "paw",
  "bone",
  "bird",
  "fish",
  "dollar",
  "credit-card",
  "receipt",
  "banknote",
  "trending-up",
  "trending-down",
  "chart",
  "target",
  "award",
  "trophy",
  "star",
  "flag",
  "wrench",
  "hammer",
  "paintbrush",
  "brush",
  "droplet",
  "flame",
  "leaf",
  "recycle",
  "tree-pine",
  "sprout",
  "hand-heart",
  "hand-coins",
  "users",
  "user",
  "rocket",
  "lightbulb",
  "settings",
  "shield",
  "lock",
  "key",
  "file",
  "clipboard",
  "calendar",
  "clock",
  "bell",
  "help",
  "plus",
];

const CATEGORY_ICON_COMPONENTS = {
  spark: Sparkles,
  house: Home,
  food: UtensilsCrossed,
  cart: ShoppingCart,
  bus: Bus,
  hospital: Stethoscope,
  utility: Zap,
  travel: Plane,
  wallet: Wallet,
  salary: Coins,
  gift: Gift,
  savings: PiggyBank,
  study: BookOpen,
  car: Car,
  entertainment: Film,
  subscription: Repeat,
  hobby: Palette,
  coffee: Coffee,
  pizza: Pizza,
  salad: Salad,
  wine: Wine,
  beef: Beef,
  "ice-cream": IceCream,
  cake: CakeSlice,
  apple: Apple,
  candy: Candy,
  cookie: Cookie,
  milk: Milk,
  egg: Egg,
  train: Train,
  bike: Bike,
  taxi: CarTaxiFront,
  ship: Ship,
  fuel: Fuel,
  parking: ParkingCircle,
  "shopping-bag": ShoppingBag,
  store: Store,
  shirt: Shirt,
  watch: Watch,
  gem: Gem,
  package: Package,
  briefcase: Briefcase,
  landmark: Landmark,
  building: Building,
  "building-2": Building2,
  warehouse: Warehouse,
  hotel: Hotel,
  trees: Trees,
  flower: Flower,
  sofa: Sofa,
  bed: Bed,
  lamp: Lamp,
  "tv-unit": Tv,
  heart: Heart,
  pill: Pill,
  syringe: Syringe,
  activity: Activity,
  "heart-pulse": HeartPulse,
  dumbbell: Dumbbell,
  music: Music,
  headphones: Headphones,
  microphone: Mic,
  gamepad: Gamepad2,
  tv: Tv2,
  theater: Theater,
  party: PartyPopper,
  ticket: Ticket,
  camera: Camera,
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  wifi: Wifi,
  phone: Phone,
  mail: Mail,
  message: MessageSquare,
  newspaper: Newspaper,
  book: Book,
  graduation: GraduationCap,
  school: School,
  pencil: Pencil,
  scissors: Scissors,
  ruler: Ruler,
  calculator: Calculator,
  globe: Globe,
  "map-pin": MapPin,
  compass: Compass,
  mountain: Mountain,
  tent: Tent,
  "palm-tree": Palmtree,
  waves: Waves,
  umbrella: Umbrella,
  sun: Sun,
  cloud: Cloud,
  snowflake: Snowflake,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  paw: PawPrint,
  bone: Bone,
  bird: Bird,
  fish: Fish,
  dollar: CircleDollarSign,
  "credit-card": CreditCard,
  receipt: Receipt,
  banknote: Banknote,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  chart: ChartBar,
  target: Target,
  award: Award,
  trophy: Trophy,
  star: Star,
  flag: Flag,
  wrench: Wrench,
  hammer: Hammer,
  paintbrush: Paintbrush,
  brush: Brush,
  droplet: Droplet,
  flame: Flame,
  leaf: Leaf,
  recycle: Recycle,
  "tree-pine": TreePine,
  sprout: Sprout,
  "hand-heart": HandHeart,
  "hand-coins": HandCoins,
  users: Users,
  user: UserCircle,
  rocket: Rocket,
  lightbulb: Lightbulb,
  settings: Settings,
  shield: Shield,
  lock: Lock,
  key: Key,
  file: FileText,
  clipboard: ClipboardList,
  calendar: Calendar,
  clock: Clock,
  bell: Bell,
  help: CircleHelp,
  plus: CirclePlus,
};

export function getCategoryIconComponent(key) {
  return CATEGORY_ICON_COMPONENTS[key] || Sparkles;
}

export function CategoryIcon({ category, size = 18, stroke = 1.8 }) {
  const Cmp = getCategoryIconComponent(category?.icon);
  return <Cmp size={size} strokeWidth={stroke} />;
}
